# Generated by Django 4.1 on 2022-08-31 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0002_alter_categories_options_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('product_image_1', models.ImageField(upload_to='')),
                ('product_image_2', models.ImageField(upload_to='')),
                ('product_image_3', models.ImageField(upload_to='')),
                ('product_image_4', models.ImageField(upload_to='')),
                ('product_description', models.TextField()),
                ('stock', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.categories')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.subcategories')),
            ],
        ),
    ]
