# Generated by Django 4.1 on 2022-09-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_product_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product'),
        ),
    ]
