# Generated by Django 4.1 on 2022-09-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=255),
        ),
    ]
