# Generated by Django 4.1 on 2022-10-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_product_price_alter_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.IntegerField(max_length=255),
        ),
    ]
