# Generated by Django 4.1 on 2022-10-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.IntegerField(default=0),
        ),
    ]
