# Generated by Django 4.1 on 2022-08-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='otp_verified',
        ),
    ]
