# Generated by Django 4.0.5 on 2022-09-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
