# Generated by Django 4.1 on 2022-09-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_categories_options_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_offer',
            field=models.IntegerField(null=True),
        ),
    ]
