# Generated by Django 4.1 on 2022-10-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_alter_categories_category_name_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='sub_category_name',
            field=models.CharField(db_index=True, max_length=225, unique=True),
        ),
    ]
