# Generated by Django 4.1 on 2022-09-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
