# Generated by Django 4.1 on 2022-09-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Conformed', 'Order Conformed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Conformed', max_length=50),
        ),
    ]
