# Generated by Django 4.1 on 2022-09-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_alter_order_payment_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Conformed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Order Confirmed', max_length=50),
        ),
    ]
