# Generated by Django 4.1 on 2022-10-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_payment_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
