# Generated by Django 4.1 on 2022-10-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_coupon_valid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_at',
            field=models.DateField(),
        ),
    ]
