# Generated by Django 4.1 on 2022-10-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_alter_coupon_valid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
