# Generated by Django 4.1 on 2022-10-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0017_coupon_used_alter_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='used',
        ),
    ]
