# Generated by Django 4.1 on 2022-10-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_remove_coupon_used_remove_coupon_user_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
