# Generated by Django 4.1 on 2022-10-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0019_alter_usercoupon_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.order'),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='total_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
