# Generated by Django 4.1 on 2022-10-03 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0021_alter_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='used',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=True)),
                ('coupone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.coupon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
