# Generated by Django 4.1 on 2022-10-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0022_alter_usercoupon_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='total_amount',
        ),
    ]
