# Generated by Django 4.1 on 2022-10-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0024_usercoupon_order_usercoupon_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
